
CREATE SCHEMA IF NOT EXISTS "test";

CREATE TABLE IF NOT EXISTS test.USERS (
  ID VARCHAR(80) DEFAULT '',
  USERNAME VARCHAR(80) DEFAULT '',
  PASSWORD VARCHAR(80) DEFAULT '',
  PRIMARY KEY(ID)
)

CREATE TABLE IF NOT EXISTS test.MEDICONES (
  ID VARCHAR(80) DEFAULT '',
  CONNECTIONDEVICEID VARCHAR(20) DEFAULT '',
  SOURCE JSONB DEFAULT '{}',  
  PRIMARY KEY(ID)
);

